"""add superseded_at to cvs

Revision ID: 4b481a8ea241
Revises: c5d09f00d1e6
Create Date: 2026-08-30 09:56:54.844326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b481a8ea241'
down_revision: Union[str, Sequence[str], None] = 'c5d09f00d1e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add cvs.superseded_at.

    Written by hand rather than autogenerated. Autogenerate compares
    the database against Base.metadata, and the two HNSW indexes
    (ix_cv_versions_embedding_hnsw, ix_jobs_embedding_hnsw) were
    created with raw op.execute() in 563b5bb86690, so they exist in
    Postgres but not in metadata. Autogenerate reads that as "removed"
    and proposes dropping them. It has done so before.

    Nullable with no server_default on purpose. NULL means "this is a
    live CV"; a timestamp means "the user replaced this one". A
    boolean would answer whether but not when, and the when is what
    makes an old row's permanently-'pending' extraction_status
    explicable rather than suspicious.
    """
    op.add_column(
        "cvs",
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("cvs", "superseded_at")
