"""add pending preference field

Revision ID: 4ca67e97fc0e
Revises: c8e2a15f4b93
Create Date: 2026-09-05 13:32:43.886041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca67e97fc0e'
down_revision: Union[str, Sequence[str], None] = 'c8e2a15f4b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pending_preference_field', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pending_preference_field')
    # ### end Alembic commands ###
