"""add pgvector extension and embedding columns

Revision ID: 563b5bb86690
Revises: 7255dfea3285
Create Date: 2026-08-28 09:54:29.178342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '563b5bb86690'
down_revision: Union[str, Sequence[str], None] = '7255dfea3285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_versions', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    op.add_column('jobs', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'embedding')
    op.drop_column('cv_versions', 'embedding')
    # ### end Alembic commands ###
"""add pgvector extension and embedding columns

Revision ID: 563b5bb86690
Revises: 7255dfea3285
Create Date: 2026-08-28 09:54:29.178342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '563b5bb86690'
down_revision: Union[str, Sequence[str], None] = '7255dfea3285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Switch on pgvector for this database. Must run before any vector
    # column is created, or Postgres won't recognise the type.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_versions', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    op.add_column('jobs', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    # ### end Alembic commands ###

    # HNSW indexes for approximate nearest-neighbour search.
    # vector_cosine_ops must match the <=> operator used at query time;
    # a mismatched opclass makes Postgres silently ignore the index.
    op.execute(
        "CREATE INDEX ix_cv_versions_embedding_hnsw "
        "ON cv_versions USING hnsw (embedding vector_cosine_ops)"
    )
    op.execute(
        "CREATE INDEX ix_jobs_embedding_hnsw "
        "ON jobs USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_jobs_embedding_hnsw")
    op.execute("DROP INDEX IF EXISTS ix_cv_versions_embedding_hnsw")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'embedding')
    op.drop_column('cv_versions', 'embedding')
    # ### end Alembic commands ###

    # The extension is deliberately NOT dropped. DROP EXTENSION cascades
    # to anything depending on it, and leaving it costs nothing.