"""add cv extraction status fields

Revision ID: c5d09f00d1e6
Revises: a41c9e2b7f30
Create Date: 2026-08-29 09:33:16.686752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d09f00d1e6'
down_revision: Union[str, Sequence[str], None] = 'a41c9e2b7f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The autogenerated diff also proposed dropping the two HNSW
    # indexes (ix_cv_versions_embedding_hnsw, ix_jobs_embedding_hnsw).
    # That is a false positive, not a real change: those indexes were
    # created with raw op.execute() in 563b5bb86690 because HNSW isn't
    # expressible through the ORM's Index() the way a plain btree is,
    # so they were never in Base.metadata for Alembic to compare
    # against. Autogenerate sees "in the database but not in metadata"
    # and assumes removed. They are left untouched here.
    op.add_column(
        'cvs',
        sa.Column(
            'extraction_status',
            sa.String(length=32),
            server_default='pending',
            nullable=False,
        ),
    )
    op.add_column('cvs', sa.Column('extraction_error', sa.Text(), nullable=True))
    op.add_column(
        'cvs', sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True)
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('cvs', 'extracted_at')
    op.drop_column('cvs', 'extraction_error')
    op.drop_column('cvs', 'extraction_status')
